# 任务板描述文件

task1:
    name: 后台登陆首页页面的制作
    status: 正在进行
    developer: 宋小萌
task2:
    name: 角色管理界面中分配角色权限的功能
    status: 正在进行
    developer: 徐长栋
task3:
    name: 系统设置中设置描述文件的制作以及seeds.rb文件中相应操作的编写
    status: 正在进行
    developer: 蒋悦达
task4:
    name: 用户登陆模块的测试编写
    status: 正在进行
    developer: 安纪存
task5:
    name: 角色权限页面分配角色时处理高级属性的功能
    status: 等待
    developer: 
task6:
    name: 获取指定用户权限信息的功能
    status: 等待
    developer: 
task7:
    name: 权限增强功能的实现
    status: 等待
    developer: 
task8:
    name: 系统设置的编辑页面中对增强功能的支持
    status: 等待
    developer: 